// Fun, varied labels for the chat "working" indicator. Picked at random per
// turn so the agent never says the same thing twice in a row.

export const WORKING_PHRASES = [
  'Cogitating',
  'Cooking',
  'Brewing',
  'Simmering',
  'Marinating',
  'Percolating',
  'Steeping',
  'Distilling',
  'Conjuring',
  'Scheming',
  'Plotting',
  'Pondering',
  'Ruminating',
  'Deliberating',
  'Musing',
  'Contemplating',
  'Meditating',
  'Calculating',
  'Crunching numbers',
  'Churning',
  'Whirring',
  'Spinning up',
  'Warming up',
  'Stretching',
  'Sharpening pencils',
  'Rolling up sleeves',
  'Cracking knuckles',
  'Consulting the archives',
  'Reading the runes',
  'Checking the crystal ball',
  'Asking the oracle',
  'Summoning context',
  'Gathering threads',
  'Weaving',
  'Knitting ideas',
  'Spinning yarns',
  'Untangling',
  'Unraveling',
  'Decoding',
  'Parsing',
  'Compiling thoughts',
  'Cross-referencing',
  'Fact-checking',
  'Double-checking',
  'Triangulating',
  'Sniffing around',
  'Digging',
  'Delving',
  'Excavating',
  'Spelunking',
  'Prospecting',
  'Panning for gold',
  'Hunting',
  'Tracking',
  'Tracing',
  'Following leads',
  'Chasing clues',
  'Sleuthing',
  'Investigating',
  'Inspecting',
  'Scrutinizing',
  'Squinting at the code',
  'Peering',
  'Zooming in',
  'Stepping back',
  'Taking stock',
  'Weighing options',
  'Balancing tradeoffs',
  'Sketching',
  'Drafting',
  'Outlining',
  'Mapping',
  'Charting',
  'Navigating',
  'Plotting a course',
  'Steering',
  'Piloting',
  'Flying the plane',
  'Warming the engines',
  'Firing up',
  'Igniting',
  'Sparking',
  'Kindling',
  'Fanning flames',
  'Stoking the fire',
  'Forging',
  'Smithing',
  'Hammering',
  'Welding',
  'Bolting',
  'Tinkering',
  'Fiddling',
  'Noodling',
  'Puttering',
  'Pottering',
  'Doodling',
  'Scribbling',
  'Jotting',
  'Highlighting',
  'Underlining',
  'Annotating',
  'Bookmarking',
  'Filing',
  'Sorting',
  'Sifting',
  'Filtering',
  'Winnowing',
  'Refining',
  'Polishing',
  'Buffing',
  'Varnishing',
  'Sanding',
  'Whittling',
  'Carving',
  'Sculpting',
  'Molding',
  'Shaping',
  'Assembling',
  'Building',
  'Constructing',
  'Bricklaying',
  'Plumbing',
  'Wiring',
  'Soldering',
  'Rubber-ducking',
  'Whispering to the compiler',
  'Bribing the compiler',
  'Negotiating with regex',
  'Taming wild pointers',
  'Herding semicolons',
  'Wrangling dependencies',
  'Untangling imports',
  'Rearranging deck chairs',
  'Painting the bikeshed',
  'Naming variables',
  'Doing the math',
  'Running the numbers',
  'Stress-testing',
  'Benchmarking',
  'Profiling',
  'Sampling',
  'Measuring twice',
  'Reading the manual',
  'Skimming the docs',
  'Recalling',
  'Connecting dots',
  'Joining dots',
  'Dotting i\u2019s',
  'Crossing t\u2019s',
  'Sweating the details',
  'Sweeping',
  'Tidying up',
  'Decluttering',
  'Taking out the trash',
  'Emptying caches',
  'Flushing buffers',
  'Rewinding',
  'Fast-forwarding',
  'Time-traveling',
  'Warping',
  'Teleporting',
  'Beaming up',
  'Loading',
  'Buffering',
  'Rendering',
  'Pixel-pushing',
  'Byte-wrangling',
  'Bit-flipping',
  'Crunching bits',
  'Spinning the fans',
  'Cooling the servers',
  'Hydrating',
  'Caffeinating',
  'Sipping coffee',
  'Snacking',
  'Taking a lap',
  'Stretching legs',
  'Breathing',
  'Centering',
  'Aligning chakras',
  'Manifesting',
  'Visualizing',
  'Envisioning',
  'Imagining',
  'Dreaming',
  'Humming',
  'Whistling',
  'Singing',
  'Vibing',
  'Grooving',
  'Jamming',
  'Composing',
  'Orchestrating',
  'Conducting',
  'Tuning instruments',
  'Setting the stage',
  'Dimming the lights',
  'Rehearsing',
  'Improvising',
  'Baking',
  'Proofing dough',
  'Kneading',
  'Chopping',
  'Dicing',
  'Julienning',
  'Saut\u00e9ing',
  'Flamb\u00e9ing',
  'Plating',
  'Garnishing',
  'Taste-testing',
  'Seasoning',
  'Stirring the pot',
  'Watching the pot',
  'Microwaving',
  'Toasting',
  'Grilling',
  'Smoking',
  'Barbecuing',
  'Fermenting',
  'Pickling',
  'Canning',
  'Whipping up',
  'Folding in',
  'Reducing the sauce',
  'Braising',
  'Roasting',
  'Poaching',
  'Caramelizing',
]

export function randomPhrase() {
  return WORKING_PHRASES[Math.floor(Math.random() * WORKING_PHRASES.length)]
}
